import { GreekLetter } from "@/app/types/game";

export const GREEK_ALPHABET: GreekLetter[] = [
  {
    id: "alpha",
    name: "Alpha",
    uppercase: "Α",
    lowercase: "α",
    pronunciation: "AL-fah",
    description: "First letter of the Greek alphabet",
  },
  {
    id: "beta",
    name: "Beta",
    uppercase: "Β",
    lowercase: "β",
    pronunciation: "BAY-tah",
    description: "Second letter of the Greek alphabet",
  },
  {
    id: "gamma",
    name: "Gamma",
    uppercase: "Γ",
    lowercase: "γ",
    pronunciation: "GAM-mah",
    description: "Third letter of the Greek alphabet",
  },
  {
    id: "delta",
    name: "Delta",
    uppercase: "Δ",
    lowercase: "δ",
    pronunciation: "DEL-tah",
    description: "Fourth letter of the Greek alphabet",
  },
  {
    id: "epsilon",
    name: "Epsilon",
    uppercase: "Ε",
    lowercase: "ε",
    pronunciation: "EP-si-lon",
    description: "Fifth letter of the Greek alphabet",
  },
  {
    id: "zeta",
    name: "Zeta",
    uppercase: "Ζ",
    lowercase: "ζ",
    pronunciation: "ZAY-tah",
    description: "Sixth letter of the Greek alphabet",
  },
  {
    id: "eta",
    name: "Eta",
    uppercase: "Η",
    lowercase: "η",
    pronunciation: "AY-tah",
    description: "Seventh letter of the Greek alphabet",
  },
  {
    id: "theta",
    name: "Theta",
    uppercase: "Θ",
    lowercase: "θ",
    pronunciation: "THAY-tah",
    description: "Eighth letter of the Greek alphabet",
  },
  {
    id: "iota",
    name: "Iota",
    uppercase: "Ι",
    lowercase: "ι",
    pronunciation: "eye-OH-tah",
    description: "Ninth letter of the Greek alphabet",
  },
  {
    id: "kappa",
    name: "Kappa",
    uppercase: "Κ",
    lowercase: "κ",
    pronunciation: "KAP-pah",
    description: "Tenth letter of the Greek alphabet",
  },
  {
    id: "lambda",
    name: "Lambda",
    uppercase: "Λ",
    lowercase: "λ",
    pronunciation: "LAM-dah",
    description: "Eleventh letter of the Greek alphabet",
  },
  {
    id: "mu",
    name: "Mu",
    uppercase: "Μ",
    lowercase: "μ",
    pronunciation: "MYOO",
    description: "Twelfth letter of the Greek alphabet",
  },
  {
    id: "nu",
    name: "Nu",
    uppercase: "Ν",
    lowercase: "ν",
    pronunciation: "NYOO",
    description: "Thirteenth letter of the Greek alphabet",
  },
  {
    id: "xi",
    name: "Xi",
    uppercase: "Ξ",
    lowercase: "ξ",
    pronunciation: "KSEE",
    description: "Fourteenth letter of the Greek alphabet",
  },
  {
    id: "omicron",
    name: "Omicron",
    uppercase: "Ο",
    lowercase: "ο",
    pronunciation: "OH-mi-kron",
    description: "Fifteenth letter of the Greek alphabet",
  },
  {
    id: "pi",
    name: "Pi",
    uppercase: "Π",
    lowercase: "π",
    pronunciation: "PIE",
    description: "Sixteenth letter of the Greek alphabet",
  },
  {
    id: "rho",
    name: "Rho",
    uppercase: "Ρ",
    lowercase: "ρ",
    pronunciation: "ROH",
    description: "Seventeenth letter of the Greek alphabet",
  },
  {
    id: "sigma",
    name: "Sigma",
    uppercase: "Σ",
    lowercase: "σ",
    pronunciation: "SIG-mah",
    description: "Eighteenth letter of the Greek alphabet",
  },
  {
    id: "tau",
    name: "Tau",
    uppercase: "Τ",
    lowercase: "τ",
    pronunciation: "TAWW",
    description: "Nineteenth letter of the Greek alphabet",
  },
  {
    id: "upsilon",
    name: "Upsilon",
    uppercase: "Υ",
    lowercase: "υ",
    pronunciation: "OOP-si-lon",
    description: "Twentieth letter of the Greek alphabet",
  },
  {
    id: "phi",
    name: "Phi",
    uppercase: "Φ",
    lowercase: "φ",
    pronunciation: "FEE",
    description: "Twenty-first letter of the Greek alphabet",
  },
  {
    id: "chi",
    name: "Chi",
    uppercase: "Χ",
    lowercase: "χ",
    pronunciation: "KEE",
    description: "Twenty-second letter of the Greek alphabet",
  },
  {
    id: "psi",
    name: "Psi",
    uppercase: "Ψ",
    lowercase: "ψ",
    pronunciation: "PSEE",
    description: "Twenty-third letter of the Greek alphabet",
  },
  {
    id: "omega",
    name: "Omega",
    uppercase: "Ω",
    lowercase: "ω",
    pronunciation: "oh-MAY-gah",
    description: "Twenty-fourth letter of the Greek alphabet",
  },
];

// Game configuration based on difficulty
export const GAME_CONFIG = {
  easy: { pairs: 6, timeLimit: 120 }, // 12 cards (6 letters)
  medium: { pairs: 9, timeLimit: 100 }, // 18 cards (9 letters)
  hard: { pairs: 12, timeLimit: 80 }, // 24 cards (12 letters)
};

export const DIFFICULTY_DESCRIPTIONS = {
  easy: "6 letters - Perfect for beginners (Α-Ζ)",
  medium: "9 letters - Build your confidence (Α-Ι)",
  hard: "12 letters - Master the alphabet (Α-Λ)",
};
